drop procedure if exists get_not_initialized_player_puuids;
create procedure get_not_initialized_player_puuids()
begin
    select
        users.puuid
    from
        registered_users users
    where
        users.has_been_initialized = false;
end;

drop procedure if exists insert_match_ids;
create procedure insert_match_ids(in p_match_ids text)
begin
    declare v_pos int;
    declare v_nextpos int;
    declare v_item varchar(255);

    set v_pos = 1;

    while v_pos < length(p_match_ids) do
        set v_nextpos = if(locate(',', p_match_ids, v_pos) > 0, locate(',', p_match_ids, v_pos), length(p_match_ids) + 1);
        set v_item = substring(p_match_ids, v_pos, v_nextpos - v_pos);

        insert ignore into match_ids (id) values (v_item);

        set v_pos = v_nextpos + 1;
    end while;
end;

drop procedure if exists mark_player_as_initialized;
create procedure mark_player_as_initialized(in p_puuid varchar(79))
begin
    update 
        registered_users 
    set 
        has_been_initialized = true,
        last_matches_check = current_timestamp
    where 
        puuid = p_puuid;
end;

drop procedure if exists get_daily_users_data_fetch;
create procedure get_daily_users_data_fetch()
begin
    select
        users.puuid
    from
        registered_users users
    where
        users.has_been_initialized = true and (users.last_matches_check + interval 1 day) <= current_timestamp;
end;

drop procedure if exists mark_player_as_completed_daily_data_fetch;
create procedure mark_player_as_completed_daily_data_fetch(in p_puuid varchar(79))
begin
    update registered_users set last_matches_check = current_timestamp where puuid = p_puuid;
end;

drop procedure if exists fetch_match_ids_with_no_data;
create procedure fetch_match_ids_with_no_data()
begin
    select
        match_ids.id
    from
        match_ids
        left join match_participants participants on participants.match_id = match_ids.id
    where
        participants.match_id is null;
end;

drop procedure if exists insert_match_data;
create procedure insert_match_data(
    in p_match_id varchar(255),
    in p_game_creation_timestamp timestamp,
    in p_game_start_timestamp timestamp,
    in p_game_end_timestamp timestamp,
    in p_game_duration int,
    in p_game_mode varchar(100),
    in p_game_type varchar(100),
    in p_map_id int
)
begin
    insert into matches (
        match_id,
        game_creation_timestamp,
        game_start_timestamp,
        game_end_timestamp,
        game_duration,
        game_mode,
        game_type,
        map_id
    ) values (
        p_match_id,
        p_game_creation_timestamp,
        p_game_start_timestamp,
        p_game_end_timestamp,
        p_game_duration,
        p_game_mode,
        p_game_type,
        p_map_id
    );
end;

drop procedure if exists insert_match_team_data;
create procedure insert_match_team_data(
    in p_match_id varchar(255),
    in p_left_team bool,
    in p_win bool,
    in p_champion_id_ban_1 int,
    in p_champion_id_ban_2 int,
    in p_champion_id_ban_3 int,
    in p_champion_id_ban_4 int,
    in p_champion_id_ban_5 int,
    in p_first_to_take_baron bool,
    in p_first_to_take_champion bool,
    in p_first_to_take_dragon bool,
    in p_first_to_take_inhibitor bool,
    in p_first_to_take_rift_herald bool,
    in p_first_to_take_tower bool,
    in p_baron_amount int,
    in p_champion_amount int,
    in p_dragon_amount int,
    in p_inhibitor_amount int,
    in p_rift_herald_amount int,
    in p_tower_amount int
)
begin
    insert into match_teams (
        match_id,
        left_team,
        win,
        champion_id_ban_1,
        champion_id_ban_2,
        champion_id_ban_3,
        champion_id_ban_4,
        champion_id_ban_5,
        first_to_take_baron,
        first_to_take_champion,
        first_to_take_dragon,
        first_to_take_inhibitor,
        first_to_take_rift_herald,
        first_to_take_tower,
        baron_amount,
        champion_amount,
        dragon_amount,
        inhibitor_amount,
        rift_herald_amount,
        tower_amount
    ) values (
        p_match_id,
        p_left_team,
        p_win,
        p_champion_id_ban_1,
        p_champion_id_ban_2,
        p_champion_id_ban_3,
        p_champion_id_ban_4,
        p_champion_id_ban_5,
        p_first_to_take_baron,
        p_first_to_take_champion,
        p_first_to_take_dragon,
        p_first_to_take_inhibitor,
        p_first_to_take_rift_herald,
        p_first_to_take_tower,
        p_baron_amount,
        p_champion_amount,
        p_dragon_amount,
        p_inhibitor_amount,
        p_rift_herald_amount,
        p_tower_amount
    );
end;

drop procedure if exists insert_match_participant_data;
create procedure insert_match_participant_data(
    in p_puuid varchar(78),
    in p_match_id varchar(255),
    in p_left_team bool,
    in p_participant_id int,
    in p_summoner_name varchar(63),
    in p_summoner_level int,
    in p_profile_icon_id int,
    in p_win bool,
    in p_game_ended_in_early_surrender bool,
    in p_game_ended_in_surrender bool,
    in p_team_early_surrendered bool,
    in p_kills int,
    in p_deaths int,
    in p_assists int,
    in p_team_position varchar(255),
    in p_time_played int,
    in p_baron_kills int,
    in p_dragon_kills int,
    in p_bounty_level int,
    in p_double_kills int,
    in p_triple_kills int,
    in p_quadra_kills int,
    in p_penta_kills int,
    in p_unreal_kills int,
    in p_killing_sprees int,
    in p_largest_killing_spree int,
    in p_largest_multi_kill int,
    in p_champion_id int,
    in p_champion_name varchar(255),
    in p_champion_experience int,
    in p_champion_level int,
    in p_champion_transform int,
    in p_primary_perk_style int,
    in p_primary_perk int,
    in p_primary_perk_var_1 int,
    in p_primary_perk_var_2 int,
    in p_primary_perk_var_3 int,
    in p_primary_perk_1 int,
    in p_primary_perk_1_var_1 int,
    in p_primary_perk_1_var_2 int,
    in p_primary_perk_1_var_3 int,
    in p_primary_perk_2 int,
    in p_primary_perk_2_var_1 int,
    in p_primary_perk_2_var_2 int,
    in p_primary_perk_2_var_3 int,
    in p_primary_perk_3 int,
    in p_primary_perk_3_var_1 int,
    in p_primary_perk_3_var_2 int,
    in p_primary_perk_3_var_3 int,
    in p_secondary_perk_style int,
    in p_secondary_perk_1 int,
    in p_secondary_perk_1_var_1 int,
    in p_secondary_perk_1_var_2 int,
    in p_secondary_perk_1_var_3 int,
    in p_secondary_perk_2 int,
    in p_secondary_perk_2_var_1 int,
    in p_secondary_perk_2_var_2 int,
    in p_secondary_perk_2_var_3 int,
    in p_stat_perk_offensive int,
    in p_stat_perk_flex int,
    in p_stat_perk_defensive int,
    in p_spell_q_casts int,
    in p_spell_w_casts int,
    in p_spell_e_casts int,
    in p_spell_r_casts int,
    in p_summoner_1_id int,
    in p_summoner_2_id int,
    in p_summoner_1_casts int,
    in p_summoner_2_casts int,
    in p_gold_earned int,
    in p_gold_spent int,
    in p_consumables_purchased int,
    in p_items_purchased int,
    in p_sight_wards_bought_in_game int,
    in p_vision_wards_bought_in_game int,
    in p_item0 int,
    in p_item1 int,
    in p_item2 int,
    in p_item3 int,
    in p_item4 int,
    in p_item5 int,
    in p_item6 int,
    in p_first_blood_assist bool,
    in p_first_blood_kill bool,
    in p_first_tower_assist bool,
    in p_first_tower_kill bool,
    in p_turret_kills int,
    in p_turret_takedowns int,
    in p_turrets_lost int,
    in p_inhibitor_kills int,
    in p_inhibitor_takedowns int,
    in p_inhibitors_lost int,
    in p_damage_dealt_to_buildings int,
    in p_damage_dealt_to_objectives int,
    in p_damage_dealt_to_turrets int,
    in p_damage_self_mitigated int,
    in p_nexus_kills int,
    in p_nexus_lost int,
    in p_nexus_takedowns int,
    in p_total_minions_killed int,
    in p_neutral_minions_killed int,
    in p_total_ally_jungle_minions_killed int,
    in p_total_enemy_jungle_minions_killed int,
    in p_total_damage_dealt int,
    in p_total_damage_dealt_to_champions int,
    in p_total_damage_shielded_on_teammates int,
    in p_total_damage_taken int,
    in p_total_heal int,
    in p_total_heals_on_teammates int,
    in p_largest_critical_strike int,
    in p_longest_time_spent_living int,
    in p_magic_damage_dealt int,
    in p_magic_damage_dealt_to_champions int,
    in p_magic_damage_taken int,
    in p_true_damage_dealt int,
    in p_true_damage_dealt_to_champions int,
    in p_true_damage_taken int,
    in p_objectives_stolen int,
    in p_objectives_stolen_assists int,
    in p_physical_damage_dealt int,
    in p_physical_damage_dealt_to_champions int,
    in p_physical_damage_taken int,
    in p_time_cc_ing_others int,
    in p_total_time_cc_dealt int,
    in p_total_time_spent_dead int,
    in p_total_units_healed int,
    in p_vision_score int,
    in p_detector_wards_placed int,
    in p_wards_killed int,
    in p_wards_placed int,
    in p_all_in_pings int,
    in p_assist_me_pings int,
    in p_bait_pings int,
    in p_basic_pings int,
    in p_command_pings int,
    in p_danger_pings int,
    in p_enemy_missing_pings int,
    in p_enemy_vision_pings int,
    in p_get_back_pings int,
    in p_hold_pings int,
    in p_need_vision_pings int,
    in p_on_my_way_pings int,
    in p_push_pings int,
    in p_vision_cleared_pings int
)
begin
    insert into match_participants (
        puuid,
        match_id,
        left_team,
        participant_id,
        summoner_name,
        summoner_level,
        profile_icon_id,
        win,
        game_ended_in_early_surrender,
        game_ended_in_surrender,
        team_early_surrendered,
        kills,
        deaths,
        assists,
        team_position,
        time_played,
        baron_kills,
        dragon_kills,
        bounty_level,
        double_kills,
        triple_kills,
        quadra_kills,
        penta_kills,
        unreal_kills,
        killing_sprees,
        largest_killing_spree,
        largest_multi_kill,
        champion_id,
        champion_name,
        champion_experience,
        champion_level,
        champion_transform,
        primary_perk_style,
        primary_perk,
        primary_perk_var_1,
        primary_perk_var_2,
        primary_perk_var_3,
        primary_perk_1,
        primary_perk_1_var_1,
        primary_perk_1_var_2,
        primary_perk_1_var_3,
        primary_perk_2,
        primary_perk_2_var_1,
        primary_perk_2_var_2,
        primary_perk_2_var_3,
        primary_perk_3,
        primary_perk_3_var_1,
        primary_perk_3_var_2,
        primary_perk_3_var_3,
        secondary_perk_style,
        secondary_perk_1,
        secondary_perk_1_var_1,
        secondary_perk_1_var_2,
        secondary_perk_1_var_3,
        secondary_perk_2,
        secondary_perk_2_var_1,
        secondary_perk_2_var_2,
        secondary_perk_2_var_3,
        stat_perk_offensive,
        stat_perk_flex,
        stat_perk_defensive,
        spell_q_casts,
        spell_w_casts,
        spell_e_casts,
        spell_r_casts,
        summoner_1_id,
        summoner_2_id,
        summoner_1_casts,
        summoner_2_casts,
        gold_earned,
        gold_spent,
        consumables_purchased,
        items_purchased,
        sight_wards_bought_in_game,
        vision_wards_bought_in_game,
        item0,
        item1,
        item2,
        item3,
        item4,
        item5,
        item6,
        first_blood_assist,
        first_blood_kill,
        first_tower_assist,
        first_tower_kill,
        turret_kills,
        turret_takedowns,
        turrets_lost,
        inhibitor_kills,
        inhibitor_takedowns,
        inhibitors_lost,
        damage_dealt_to_buildings,
        damage_dealt_to_objectives,
        damage_dealt_to_turrets,
        damage_self_mitigated,
        nexus_kills,
        nexus_lost,
        nexus_takedowns,
        total_minions_killed,
        neutral_minions_killed,
        total_ally_jungle_minions_killed,
        total_enemy_jungle_minions_killed,
        total_damage_dealt,
        total_damage_dealt_to_champions,
        total_damage_shielded_on_teammates,
        total_damage_taken,
        total_heal,
        total_heals_on_teammates,
        largest_critical_strike,
        longest_time_spent_living,
        magic_damage_dealt,
        magic_damage_dealt_to_champions,
        magic_damage_taken,
        true_damage_dealt,
        true_damage_dealt_to_champions,
        true_damage_taken,
        objectives_stolen,
        objectives_stolen_assists,
        physical_damage_dealt,
        physical_damage_dealt_to_champions,
        physical_damage_taken,
        time_cc_ing_others,
        total_time_cc_dealt,
        total_time_spent_dead,
        total_units_healed,
        vision_score,
        detector_wards_placed,
        wards_killed,
        wards_placed,
        all_in_pings,
        assist_me_pings,
        bait_pings,
        basic_pings,
        command_pings,
        danger_pings,
        enemy_missing_pings,
        enemy_vision_pings,
        get_back_pings,
        hold_pings,
        need_vision_pings,
        on_my_way_pings,
        push_pings,
        vision_cleared_pings
    ) values (
        p_puuid,
        p_match_id,
        p_left_team,
        p_participant_id,
        p_summoner_name,
        p_summoner_level,
        p_profile_icon_id,
        p_win,
        p_game_ended_in_early_surrender,
        p_game_ended_in_surrender,
        p_team_early_surrendered,
        p_kills,
        p_deaths,
        p_assists,
        p_team_position,
        p_time_played,
        p_baron_kills,
        p_dragon_kills,
        p_bounty_level,
        p_double_kills,
        p_triple_kills,
        p_quadra_kills,
        p_penta_kills,
        p_unreal_kills,
        p_killing_sprees,
        p_largest_killing_spree,
        p_largest_multi_kill,
        p_champion_id,
        p_champion_name,
        p_champion_experience,
        p_champion_level,
        p_champion_transform,
        p_primary_perk_style,
        p_primary_perk,
        p_primary_perk_var_1,
        p_primary_perk_var_2,
        p_primary_perk_var_3,
        p_primary_perk_1,
        p_primary_perk_1_var_1,
        p_primary_perk_1_var_2,
        p_primary_perk_1_var_3,
        p_primary_perk_2,
        p_primary_perk_2_var_1,
        p_primary_perk_2_var_2,
        p_primary_perk_2_var_3,
        p_primary_perk_3,
        p_primary_perk_3_var_1,
        p_primary_perk_3_var_2,
        p_primary_perk_3_var_3,
        p_secondary_perk_style,
        p_secondary_perk_1,
        p_secondary_perk_1_var_1,
        p_secondary_perk_1_var_2,
        p_secondary_perk_1_var_3,
        p_secondary_perk_2,
        p_secondary_perk_2_var_1,
        p_secondary_perk_2_var_2,
        p_secondary_perk_2_var_3,
        p_stat_perk_offensive,
        p_stat_perk_flex,
        p_stat_perk_defensive,
        p_spell_q_casts,
        p_spell_w_casts,
        p_spell_e_casts,
        p_spell_r_casts,
        p_summoner_1_id,
        p_summoner_2_id,
        p_summoner_1_casts,
        p_summoner_2_casts,
        p_gold_earned,
        p_gold_spent,
        p_consumables_purchased,
        p_items_purchased,
        p_sight_wards_bought_in_game,
        p_vision_wards_bought_in_game,
        p_item0,
        p_item1,
        p_item2,
        p_item3,
        p_item4,
        p_item5,
        p_item6,
        p_first_blood_assist,
        p_first_blood_kill,
        p_first_tower_assist,
        p_first_tower_kill,
        p_turret_kills,
        p_turret_takedowns,
        p_turrets_lost,
        p_inhibitor_kills,
        p_inhibitor_takedowns,
        p_inhibitors_lost,
        p_damage_dealt_to_buildings,
        p_damage_dealt_to_objectives,
        p_damage_dealt_to_turrets,
        p_damage_self_mitigated,
        p_nexus_kills,
        p_nexus_lost,
        p_nexus_takedowns,
        p_total_minions_killed,
        p_neutral_minions_killed,
        p_total_ally_jungle_minions_killed,
        p_total_enemy_jungle_minions_killed,
        p_total_damage_dealt,
        p_total_damage_dealt_to_champions,
        p_total_damage_shielded_on_teammates,
        p_total_damage_taken,
        p_total_heal,
        p_total_heals_on_teammates,
        p_largest_critical_strike,
        p_longest_time_spent_living,
        p_magic_damage_dealt,
        p_magic_damage_dealt_to_champions,
        p_magic_damage_taken,
        p_true_damage_dealt,
        p_true_damage_dealt_to_champions,
        p_true_damage_taken,
        p_objectives_stolen,
        p_objectives_stolen_assists,
        p_physical_damage_dealt,
        p_physical_damage_dealt_to_champions,
        p_physical_damage_taken,
        p_time_cc_ing_others,
        p_total_time_cc_dealt,
        p_total_time_spent_dead,
        p_total_units_healed,
        p_vision_score,
        p_detector_wards_placed,
        p_wards_killed,
        p_wards_placed,
        p_all_in_pings,
        p_assist_me_pings,
        p_bait_pings,
        p_basic_pings,
        p_command_pings,
        p_danger_pings,
        p_enemy_missing_pings,
        p_enemy_vision_pings,
        p_get_back_pings,
        p_hold_pings,
        p_need_vision_pings,
        p_on_my_way_pings,
        p_push_pings,
        p_vision_cleared_pings
    );
end;

drop procedure if exists insert_match_participant_challenges_data;
create procedure insert_match_participant_challenges_data(
    in p_puuid varchar(78),
    in p_match_id varchar(255),
    in p_12_assist_streak_count float,
    in p_ability_uses float,
    in p_aces_before_15_minutes float,
    in p_allied_jungle_monster_kills float,
    in p_baron_buff_gold_advantage_over_threshold float,
    in p_baron_takedowns float,
    in p_blast_cone_opposite_opponent_count float,
    in p_bounty_gold float,
    in p_buffs_stolen float,
    in p_complete_support_quest_in_time float,
    in p_control_wards_placed float,
    in p_control_ward_time_coverage_in_river_or_enemy_half float,
    in p_damage_per_minute float,
    in p_damage_taken_on_team_percentage float,
    in p_danced_with_rift_herald float,
    in p_deaths_by_enemy_champs float,
    in p_dodge_skill_shots_small_window float,
    in p_double_aces float,
    in p_dragon_takedowns float,
    in p_earliest_baron float,
    in p_earliest_dragon_takedown float,
    in p_earliest_elder_dragon float,
    in p_early_laning_phase_gold_exp_advantage float,
    in p_effective_heal_and_shielding float,
    in p_elder_dragon_kills_with_opposing_soul float,
    in p_elder_dragon_multikills float,
    in p_enemy_champion_immobilizations float,
    in p_enemy_jungle_monster_kills float,
    in p_epic_monster_kills_near_enemy_jungler float,
    in p_epic_monster_kills_within_30_seconds_of_spawn float,
    in p_epic_monster_steals float,
    in p_epic_monster_stolen_without_smite float,
    in p_faster_support_quest_completion float,
    in p_fastest_legendary float,
    in p_first_turret_killed float,
    in p_first_turret_killed_time float,
    in p_flawless_aces float,
    in p_full_team_takedown float,
    in p_game_length float,
    in p_get_takedowns_in_all_lanes_early_jungle_as_laner float,
    in p_gold_per_minute float,
    in p_had_afk_teammate float,
    in p_had_open_nexus float,
    in p_highest_champion_damage float,
    in p_highest_crowd_control_score float,
    in p_highest_ward_kills float,
    in p_immobilize_and_kill_with_ally float,
    in p_initial_buff_count float,
    in p_initial_crab_count float,
    in p_jungle_cs_before_10_minutes float,
    in p_jungler_kills_early_jungle float,
    in p_jungler_takedowns_near_damaged_epic_monster float,
    in p_k_turrets_destroyed_before_plates_fall float,
    in p_kda float,
    in p_kill_after_hidden_with_ally float,
    in p_kill_participation float,
    in p_killed_champ_took_full_team_damage_survived float,
    in p_killing_sprees float,
    in p_kills_near_enemy_turret float,
    in p_kills_on_laners_early_jungle_as_jungler float,
    in p_kills_on_other_lanes_early_jungle_as_laner float,
    in p_kills_on_recently_healed_by_aram_pack float,
    in p_kills_under_own_turret float,
    in p_kills_with_help_from_epic_monster float,
    in p_knock_enemy_into_team_and_kill float,
    in p_land_skill_shots_early_game float,
    in p_lane_minions_first_10_minutes float,
    in p_laning_phase_gold_exp_advantage float,
    in p_legendary_count float,
    in p_lost_an_inhibitor float,
    in p_max_cs_advantage_on_lane_opponent float,
    in p_max_kill_deficit float,
    in p_max_level_lead_lane_opponent float,
    in p_mejais_full_stack_in_time float,
    in p_more_enemy_jungle_than_opponent float,
    in p_most_wards_destroyed_one_sweeper float,
    in p_multi_kill_one_spell float,
    in p_multikills float,
    in p_multikills_after_aggressive_flash float,
    in p_multi_turret_rift_herald_count float,
    in p_mythic_item_used float,
    in p_outer_turret_executes_before_10_minutes float,
    in p_outnumbered_kills float,
    in p_outnumbered_nexus_kill float,
    in p_perfect_dragon_souls_taken float,
    in p_perfect_game float,
    in p_pick_kill_with_ally float,
    in p_played_champ_select_position float,
    in p_poro_explosions float,
    in p_quick_cleanse float,
    in p_quick_first_turret float,
    in p_quick_solo_kills float,
    in p_rift_herald_takedowns float,
    in p_save_ally_from_death float,
    in p_scuttle_crab_kills float,
    in p_shortest_time_to_ace_from_first_takedown float,
    in p_skillshots_dodged float,
    in p_skillshots_hit float,
    in p_snowballs_hit float,
    in p_solo_baron_kills float,
    in p_solo_turrets_lategame float,
    in p_solo_kills float,
    in p_stealth_wards_placed float,
    in p_survived_single_digit_hp_count float,
    in p_survived_three_immobilizes_in_fight float,
    in p_takedown_on_first_turret float,
    in p_takedowns float,
    in p_takedowns_after_gaining_level_advantage float,
    in p_takedowns_before_jungle_minion_spawn float,
    in p_takedowns_first_xminutes float,
    in p_takedowns_first_25_minutes float,
    in p_takedowns_in_alcove float,
    in p_takedowns_in_enemy_fountain float,
    in p_team_baron_kills float,
    in p_team_damage_percentage float,
    in p_team_elder_dragon_kills float,
    in p_team_rift_herald_kills float,
    in p_teleport_takedowns float,
    in p_third_inhibitor_destroyed_time float,
    in p_three_wards_one_sweeper_count float,
    in p_took_large_damage_survived float,
    in p_turret_plates_taken float,
    in p_turret_takedowns float,
    in p_turrets_taken_with_rift_herald float,
    in p_twenty_minions_in_3_seconds_count float,
    in p_two_wards_one_sweeper_count float,
    in p_unseen_recalls float,
    in p_vision_score_advantage_lane_opponent float,
    in p_vision_score_per_minute float,
    in p_ward_takedowns float,
    in p_ward_takedowns_before_20_m float,
    in p_wards_guarded float
)
begin
    insert into match_participant_challenges (
        puuid,
        match_id,
        12_assist_streak_count,
        ability_uses,
        aces_before_15_minutes,
        allied_jungle_monster_kills,
        baron_buff_gold_advantage_over_threshold,
        baron_takedowns,
        blast_cone_opposite_opponent_count,
        bounty_gold,
        buffs_stolen,
        complete_support_quest_in_time,
        control_wards_placed,
        control_ward_time_coverage_in_river_or_enemy_half,
        damage_per_minute,
        damage_taken_on_team_percentage,
        danced_with_rift_herald,
        deaths_by_enemy_champs,
        dodge_skill_shots_small_window,
        double_aces,
        dragon_takedowns,
        earliest_baron,
        earliest_dragon_takedown,
        earliest_elder_dragon,
        early_laning_phase_gold_exp_advantage,
        effective_heal_and_shielding,
        elder_dragon_kills_with_opposing_soul,
        elder_dragon_multikills,
        enemy_champion_immobilizations,
        enemy_jungle_monster_kills,
        epic_monster_kills_near_enemy_jungler,
        epic_monster_kills_within_30_seconds_of_spawn,
        epic_monster_steals,
        epic_monster_stolen_without_smite,
        faster_support_quest_completion,
        fastest_legendary,
        first_turret_killed,
        first_turret_killed_time,
        flawless_aces,
        full_team_takedown,
        game_length,
        get_takedowns_in_all_lanes_early_jungle_as_laner,
        gold_per_minute,
        had_afk_teammate,
        had_open_nexus,
        highest_champion_damage,
        highest_crowd_control_score,
        highest_ward_kills,
        immobilize_and_kill_with_ally,
        initial_buff_count,
        initial_crab_count,
        jungle_cs_before_10_minutes,
        jungler_kills_early_jungle,
        jungler_takedowns_near_damaged_epic_monster,
        k_turrets_destroyed_before_plates_fall,
        kda,
        kill_after_hidden_with_ally,
        kill_participation,
        killed_champ_took_full_team_damage_survived,
        killing_sprees,
        kills_near_enemy_turret,
        kills_on_laners_early_jungle_as_jungler,
        kills_on_other_lanes_early_jungle_as_laner,
        kills_on_recently_healed_by_aram_pack,
        kills_under_own_turret,
        kills_with_help_from_epic_monster,
        knock_enemy_into_team_and_kill,
        land_skill_shots_early_game,
        lane_minions_first_10_minutes,
        laning_phase_gold_exp_advantage,
        legendary_count,
        lost_an_inhibitor,
        max_cs_advantage_on_lane_opponent,
        max_kill_deficit,
        max_level_lead_lane_opponent,
        mejais_full_stack_in_time,
        more_enemy_jungle_than_opponent,
        most_wards_destroyed_one_sweeper,
        multi_kill_one_spell,
        multikills,
        multikills_after_aggressive_flash,
        multi_turret_rift_herald_count,
        mythic_item_used,
        outer_turret_executes_before_10_minutes,
        outnumbered_kills,
        outnumbered_nexus_kill,
        perfect_dragon_souls_taken,
        perfect_game,
        pick_kill_with_ally,
        played_champ_select_position,
        poro_explosions,
        quick_cleanse,
        quick_first_turret,
        quick_solo_kills,
        rift_herald_takedowns,
        save_ally_from_death,
        scuttle_crab_kills,
        shortest_time_to_ace_from_first_takedown,
        skillshots_dodged,
        skillshots_hit,
        snowballs_hit,
        solo_baron_kills,
        solo_turrets_lategame,
        solo_kills,
        stealth_wards_placed,
        survived_single_digit_hp_count,
        survived_three_immobilizes_in_fight,
        takedown_on_first_turret,
        takedowns,
        takedowns_after_gaining_level_advantage,
        takedowns_before_jungle_minion_spawn,
        takedowns_first_xminutes,
        takedowns_first_25_minutes,
        takedowns_in_alcove,
        takedowns_in_enemy_fountain,
        team_baron_kills,
        team_damage_percentage,
        team_elder_dragon_kills,
        team_rift_herald_kills,
        teleport_takedowns,
        third_inhibitor_destroyed_time,
        three_wards_one_sweeper_count,
        took_large_damage_survived,
        turret_plates_taken,
        turret_takedowns,
        turrets_taken_with_rift_herald,
        twenty_minions_in_3_seconds_count,
        two_wards_one_sweeper_count,
        unseen_recalls,
        vision_score_advantage_lane_opponent,
        vision_score_per_minute,
        ward_takedowns,
        ward_takedowns_before_20_m,
        wards_guarded
    ) values (
        p_puuid,
        p_match_id,
        p_12_assist_streak_count,
        p_ability_uses,
        p_aces_before_15_minutes,
        p_allied_jungle_monster_kills,
        p_baron_buff_gold_advantage_over_threshold,
        p_baron_takedowns,
        p_blast_cone_opposite_opponent_count,
        p_bounty_gold,
        p_buffs_stolen,
        p_complete_support_quest_in_time,
        p_control_wards_placed,
        p_control_ward_time_coverage_in_river_or_enemy_half,
        p_damage_per_minute,
        p_damage_taken_on_team_percentage,
        p_danced_with_rift_herald,
        p_deaths_by_enemy_champs,
        p_dodge_skill_shots_small_window,
        p_double_aces,
        p_dragon_takedowns,
        p_earliest_baron,
        p_earliest_dragon_takedown,
        p_earliest_elder_dragon,
        p_early_laning_phase_gold_exp_advantage,
        p_effective_heal_and_shielding,
        p_elder_dragon_kills_with_opposing_soul,
        p_elder_dragon_multikills,
        p_enemy_champion_immobilizations,
        p_enemy_jungle_monster_kills,
        p_epic_monster_kills_near_enemy_jungler,
        p_epic_monster_kills_within_30_seconds_of_spawn,
        p_epic_monster_steals,
        p_epic_monster_stolen_without_smite,
        p_faster_support_quest_completion,
        p_fastest_legendary,
        p_first_turret_killed,
        p_first_turret_killed_time,
        p_flawless_aces,
        p_full_team_takedown,
        p_game_length,
        p_get_takedowns_in_all_lanes_early_jungle_as_laner,
        p_gold_per_minute,
        p_had_afk_teammate,
        p_had_open_nexus,
        p_highest_champion_damage,
        p_highest_crowd_control_score,
        p_highest_ward_kills,
        p_immobilize_and_kill_with_ally,
        p_initial_buff_count,
        p_initial_crab_count,
        p_jungle_cs_before_10_minutes,
        p_jungler_kills_early_jungle,
        p_jungler_takedowns_near_damaged_epic_monster,
        p_k_turrets_destroyed_before_plates_fall,
        p_kda,
        p_kill_after_hidden_with_ally,
        p_kill_participation,
        p_killed_champ_took_full_team_damage_survived,
        p_killing_sprees,
        p_kills_near_enemy_turret,
        p_kills_on_laners_early_jungle_as_jungler,
        p_kills_on_other_lanes_early_jungle_as_laner,
        p_kills_on_recently_healed_by_aram_pack,
        p_kills_under_own_turret,
        p_kills_with_help_from_epic_monster,
        p_knock_enemy_into_team_and_kill,
        p_land_skill_shots_early_game,
        p_lane_minions_first_10_minutes,
        p_laning_phase_gold_exp_advantage,
        p_legendary_count,
        p_lost_an_inhibitor,
        p_max_cs_advantage_on_lane_opponent,
        p_max_kill_deficit,
        p_max_level_lead_lane_opponent,
        p_mejais_full_stack_in_time,
        p_more_enemy_jungle_than_opponent,
        p_most_wards_destroyed_one_sweeper,
        p_multi_kill_one_spell,
        p_multikills,
        p_multikills_after_aggressive_flash,
        p_multi_turret_rift_herald_count,
        p_mythic_item_used,
        p_outer_turret_executes_before_10_minutes,
        p_outnumbered_kills,
        p_outnumbered_nexus_kill,
        p_perfect_dragon_souls_taken,
        p_perfect_game,
        p_pick_kill_with_ally,
        p_played_champ_select_position,
        p_poro_explosions,
        p_quick_cleanse,
        p_quick_first_turret,
        p_quick_solo_kills,
        p_rift_herald_takedowns,
        p_save_ally_from_death,
        p_scuttle_crab_kills,
        p_shortest_time_to_ace_from_first_takedown,
        p_skillshots_dodged,
        p_skillshots_hit,
        p_snowballs_hit,
        p_solo_baron_kills,
        p_solo_turrets_lategame,
        p_solo_kills,
        p_stealth_wards_placed,
        p_survived_single_digit_hp_count,
        p_survived_three_immobilizes_in_fight,
        p_takedown_on_first_turret,
        p_takedowns,
        p_takedowns_after_gaining_level_advantage,
        p_takedowns_before_jungle_minion_spawn,
        p_takedowns_first_xminutes,
        p_takedowns_first_25_minutes,
        p_takedowns_in_alcove,
        p_takedowns_in_enemy_fountain,
        p_team_baron_kills,
        p_team_damage_percentage,
        p_team_elder_dragon_kills,
        p_team_rift_herald_kills,
        p_teleport_takedowns,
        p_third_inhibitor_destroyed_time,
        p_three_wards_one_sweeper_count,
        p_took_large_damage_survived,
        p_turret_plates_taken,
        p_turret_takedowns,
        p_turrets_taken_with_rift_herald,
        p_twenty_minions_in_3_seconds_count,
        p_two_wards_one_sweeper_count,
        p_unseen_recalls,
        p_vision_score_advantage_lane_opponent,
        p_vision_score_per_minute,
        p_ward_takedowns,
        p_ward_takedowns_before_20_m,
        p_wards_guarded
    );
end;