create table game_modes(
    mode varchar(100) not null,

    constraint game_modes_pk primary key (mode)
);

create table game_types(
    type varchar(100) not null,

    constraint game_type_pk primary key (type)
);

create table stat_perks(
    perk varchar(100) not null,

    constraint stat_perks_pk primary key (perk)
);

create table map_ids(
    id int not null,
    name varchar(255) not null,

    constraint map_ids_pk primary key (id)
);


create table registered_users(
    puuid varchar(78) not null,
    account_id varchar(56) not null unique,
    summoner_id varchar(63) not null unique,
    game_name varchar(255) not null,
    tag_line varchar(255) not null,
    summoner_name varchar(255) not null,
    
    constraint registered_users_pk primary key (puuid)
);

create table match_ids(
    id varchar(255) not null,

    constraint match_ids_pk primary key (id)
);

create table matches(
    id varchar(255) not null,
    game_creation timestamp not null,
    game_start_time timestamp not null,
    game_end_timestamp timestamp not null,
    game_duration int not null,
    game_mode varchar(100) not null,
    game_type varchar(100) not null,
    map_id int not null,
    
    constraint matches_pk primary key (id),
    constraint matches_match_id foreign key (id) references match_ids(id),
    constraint matches_game_mode foreign key (game_mode) references game_modes(mode),
    constraint matches_game_type foreign key (game_type) references game_types(type),
    constraint matches_map_id foreign key (map_id) references map_ids(id)
);

create table match_participant_challenges(
    puuid varchar(78) not null,
    match_id varchar(255) not null,
    
    12_assist_streak_count int not null,
    ability_uses int not null,
    aces_before_15_minutes int not null,
    allied_jungle_monster_kills int not null,
    baron_takedowns int not null,
    blast_cone_opposite_opponent_count int not null,
    bounty_gold int not null,
    buffs_stolen int not null,
    complete_support_quest_in_time int not null,
    control_wards_placed int not null,
    damage_per_minute float not null,
    damage_taken_on_team_percentage float not null,
    danced_with_rift_herald char not null,
    deaths_by_enemy_champs int not null,
    dodge_skill_shots_small_window int not null,
    double_aces int not null,
    dragon_takedowns int not null,
    earliest_dragon_takedown float,
    early_laning_phase_gold_exp_advantage char not null,
    effective_heal_and_shielding float not null,
    elder_dragon_kills_with_opposing_soul int not null,
    elder_dragon_multikills int not null,
    enemy_champion_immobilizations int not null,
    enemy_jungle_monster_kills int not null,
    epic_monster_kills_near_enemy_jungler int not null,
    epic_monster_kills_within_30_seconds_of_spawn int not null,
    epic_monster_steals int not null,
    epic_monster_stolen_without_smite int not null,
    first_turret_killed char not null,
    first_turret_killed_time float,
    flawless_aces int not null,
    full_team_takedown int not null,
    game_length float not null,
    get_takedowns_in_all_lanes_early_jungle_as_laner char not null,
    gold_per_minute float not null,
    had_open_nexus char not null,
    immobilize_and_kill_with_ally int not null,
    initial_buff_count int not null,
    initial_crab_count int not null,
    jungle_cs_before_10_minutes int not null,
    jungler_kills_early_jungle int not null,
    jungler_takedowns_near_damaged_epic_monster int not null,
    k_turrets_destroyed_before_plates_fall int not null,
    kda float not null,
    kill_after_hidden_with_ally int not null,
    kill_participation float not null,
    killed_champ_took_full_team_damage_survived int not null,
    killing_sprees int not null,
    kills_near_enemy_turret int not null,
    kills_on_laners_early_jungle_as_jungler int not null,
    kills_on_recently_healed_by_aram_pack int not null,
    kills_under_own_turret int not null,
    kills_with_help_from_epic_monster int not null,
    knock_enemy_into_team_and_kill int not null,
    land_skill_shots_early_game int not null,
    lane_minions_first_10_minutes int not null,
    laning_phase_gold_exp_advantage char not null,
    legendary_count int not null,
    lost_an_inhibitor char not null,
    max_cs_advantage_on_lane_opponent int not null,
    max_kill_deficit int not null,
    max_level_lead_lane_opponent int not null,
    mejais_full_stack_in_time int not null,
    more_enemy_jungle_than_opponent char not null,
    multi_kill_one_spell int not null,
    multi_turret_rift_herald_count int not null,
    multikills int not null,
    multikills_after_aggressive_flash int not null,
    outer_turret_executes_before_10_minutes int not null,
    outnumbered_kills int not null,
    outnumbered_nexus_kill int not null,
    perfect_dragon_souls_taken int not null,
    perfect_game char not null,
    pick_kill_with_ally int not null,
    played_champ_select_position char not null,
    poro_explosions int not null,
    quick_cleanse int not null,
    quick_first_turret char not null,
    quick_solo_kills int not null,
    rift_herald_takedowns int not null,
    save_ally_from_death int not null,
    scuttle_crab_kills int not null,
    skillshots_dodged int not null,
    skillshots_hit int not null,
    snowballs_hit int not null,
    solo_baron_kills int not null,
    solo_kills int not null,
    stealth_wards_placed int not null,
    survived_single_digit_hp_count int not null,
    survived_three_immobilizes_in_fight int not null,
    takedown_on_first_turret int not null,
    takedowns int not null,
    takedowns_after_gaining_level_advantage int not null,
    takedowns_before_jungle_minion_spawn int not null,
    takedowns_first_xminutes int not null,
    takedowns_in_alcove int not null,
    takedowns_in_enemy_fountain int not null,
    team_baron_kills int not null,
    team_damage_percentage float not null,
    team_elder_dragon_kills int not null,
    team_rift_herald_kills int not null,
    took_large_damage_survived int not null,
    turret_plates_taken int not null,
    turret_takedowns int not null,
    turrets_taken_with_rift_herald int not null,
    twenty_minions_in_3_seconds_count int not null,
    two_wards_one_sweeper_count int not null,
    unseen_recalls int not null,
    vision_score_advantage_lane_opponent char not null,
    vision_score_per_minute float not null,
    ward_takedowns int not null,
    ward_takedowns_before_20_m int not null,
    wards_guarded int not null,

    constraint match_participant_challenges_pk primary key (puuid, match_id),
    constraint match_participant_challenges_puuid foreign key (puuid) references registered_users(puuid),
    constraint match_participant_challenges_match_id foreign key (match_id) references matches(id)
);

create table match_participants(
    puuid varchar(78) not null,
    match_id varchar(255) not null,
    left_team char not null,
    participant_id int not null,
    
    summoner_name varchar(63) not null,
    summoner_level int not null,
    profile_icon_id int not null,
    
    win char not null,
    game_ended_in_early_surrender char not null,
    game_ended_in_surrender char not null,
    team_early_surrendered char not null,
    
    kills int not null,
    deaths int not null,
    assists int not null,
    team_position varchar(255) not null,
    time_played int not null,
    baron_kills int not null,
    dragon_kills int not null,
    bounty_level int not null,
    
    double_kills int not null,
    triple_kills int not null,
    quadra_kills int not null,
    penta_kills int not null,
    unreal_kills int not null,
    killing_sprees int not null,
    largest_killing_spree int not null,
    largest_multi_kill int not null,
    
    champion_id int not null,
    champion_name varchar(255) not null,
    champion_experience int not null,
    champion_level int not null,
    champion_transform int not null,
    banned_champion_id int,
    
    primary_perk_style int not null,
    primary_perk int not null,
    primary_perk_1 int not null,
    primary_perk_2 int not null,
    primary_perk_3 int not null,
    secondary_perk_style int not null,
    secondary_perk_1 int not null,
    secondary_perk_2 int not null,
    
    stat_perk_offensive varchar(50) not null,
    stat_perk_flex varchar(50) not null,
    stat_perk_defensive varchar(50) not null,
    
    spell_q_casts int not null,
    spell_w_casts int not null,
    spell_e_casts int not null,
    spell_r_casts int not null,
    summoner_1_id int not null,
    summoner_2_id int not null,
    summoner_1_casts int not null,
    summoner_2_casts int not null,
    
    gold_earned int not null,
    gold_spent int not null,
    consumables_purchased int not null,
    items_purchased int not null,
    sight_wards_bought_in_game int not null,
    vision_wards_bought_in_game int not null,
    item0 int not null,
    item1 int not null,
    item2 int not null,
    item3 int not null,
    item4 int not null,
    item5 int not null,
    item6 int not null,

    first_blood_assist char not null,
    first_blood_kill char not null,
    first_tower_assist char not null,
    first_tower_kill char not null,
    turret_kills int not null,
    turret_takedowns int not null,
    turrets_lost int not null,
    inhibitor_kills int not null,
    inhibitor_takedowns int not null,
    inhibitors_lost int not null,
    damage_dealt_to_buildings int not null,
    damage_dealt_to_objectives int not null,
    damage_dealt_to_turrets int not null,
    damage_self_mitigated int not null,
    nexus_kills int not null,
    nexus_lost int not null,
    nexus_takedowns int not null,
    total_minions_killed int not null,
    neutral_minions_killed int not null,
    total_ally_jungle_minions_killed int not null,
    total_enemy_jungle_minions_killed int not null,
    total_damage_dealt int not null,
    total_damage_dealt_to_champions int not null,
    total_damage_shielded_on_teammates int not null,
    total_damage_taken int not null,
    total_heal int not null,
    total_heals_on_teammates int not null,
    largest_critical_strike int not null,
    longest_time_spent_living int not null,
    magic_damage_dealt int not null,
    magic_damage_dealt_to_champions int not null,
    magic_damage_taken int not null,
    true_damage_dealt int not null,
    true_damage_dealt_to_champions int not null,
    true_damage_taken int not null,
    objectives_stolen int not null,
    objectives_stolen_assists int not null,
    physical_damage_dealt int not null,
    physical_damage_dealt_to_champions int not null,
    physical_damage_taken int not null,
    time_cc_ing_others int not null,
    total_time_cc_dealt int not null,
    total_time_spent_dead int not null,
    total_units_healed int not null,
    
    vision_score int not null,
    detector_wards_placed int not null,
    wards_killed int not null,
    wards_placed int not null,

    all_in_pings int not null,
    assist_me_pings int not null,
    bait_pings int not null,
    basic_pings int not null,
    command_pings int not null,
    danger_pings int not null,
    enemy_missing_pings int not null,
    enemy_vision_pings int not null,
    get_back_pings int not null,
    hold_pings int not null,
    need_vision_pings int not null,
    on_my_way_pings int not null,
    push_pings int not null,
    vision_cleared_pings int not null,

    constraint match_participants_pk primary key (puuid, match_id),
    constraint match_participants_puuid foreign key (puuid) references registered_users(puuid),
    constraint match_participants_match_id foreign key (match_id) references matches(id),
    constraint match_participants_stat_perk_offensive foreign key (stat_perk_offensive) references stat_perks(perk),
    constraint match_participants_stat_perk_flex foreign key (stat_perk_flex) references stat_perks(perk),
    constraint match_participants_stat_perk_defensive foreign key (stat_perk_defensive) references stat_perks(perk)
);